django user login logout/user_login_logout/register_app/urls.py
from django.urls import path
from register_app import views


app_name="register_app"

urlpatterns=[
    path("register/",views.register,name='register'),
    path("login/",views.user_login,name='user_login'),
]

django user login logout/user_login_logout/user_login_logout/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from register_app import views

urlpatterns = [
    path("",views.index,name='index'),
    path('register_app/',include('register_app.urls')),
    path("logout/",views.user_logout,name="user_logout"),
    path('admin/', admin.site.urls),
]

django user login logout/user_login_logout/register_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):

    # user is instance of User model
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    ##additional information added to User and name the model UserProfileInfo

    portfolio_link=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to="profile_pics",blank=True)

    def __str__(self):
        return self.user.username
        ##username is the field inside User

django user login logout/user_login_logout/register_app/forms.py
from django import forms
from register_app.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):

    #validation for the name goes here
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields=('username','first_name','last_name','email','password')

class UserProfileInfoForm(forms.ModelForm):

    ##validation for fields under UserProfileInfo

    class Meta:
        model=UserProfileInfo
        fields=("portfolio_link","profile_pic")

django user login logout/user_login_logout/register_app/views.py
from django.shortcuts import render
from register_app.forms import UserForm,UserProfileInfoForm

#imports require for login
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required



# Create your views here.
#Home page view
def index(request):
    return render(request,"register_app/index.html")

#for logout
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



#Register page view
def register(request):
    registered=False

    if request.method=="POST":
        user_form = UserForm(data=request.POST)  #tag for UserForm
        profile_form = UserProfileInfoForm(data=request.POST) #tag for UserProfileInfoForm


        #check for validation of input provided by user
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()  #save to the Database
            user.set_password(user.password)  #hash the password
            user.save()  #save the hash password in the databases

            profile=profile_form.save(commit=False) #dont commit data to the databases
            profile.user=user     #for one to one relationship

            if 'profile_pic' in request.FILES:
                print("Under profile pic")
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()    #update data to the Database

            registered=True

        else:    #in case if there is error in validation of input data
            print(user_form.errors,profile_form.errors)
    else:      #in case if the method is not post
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    context_dic={"user_form":user_form,"profile_form":profile_form,"registered":registered}
    return render(request,"register_app/register.html",context_dic)




#login views

def user_login(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password= request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("<h3>Account is not active</h3>")

        else:
            #print will print the stuff on the console
            print("Someone try to login in your account")
            print("Entered Username:{} and Password:{}".format(username,password))
            return HttpResponse("<h2>Invalid Username or Password</h2>")

    else:
        return render(request,"register_app/login.html",{})

django user login logout/user_login_logout/templates/register_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id='navbarNav'>
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="navbar-brand" href="{% url "index" %}">INDEX</a>
          </li>
          <li class='nav-item'>
            <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
          </li>
          <li class='nav-item'>
            <a class="nav-link" href="{%url "register_app:register"%}">Register</a>
          </li>
          {% if user.is_authenticated %}
          <li class='nav-item'>
            <a class='nav-link' href="{% url "user_logout"%}">Logout</a>
          </li>
            {% else %}
          <li>
              <a class='nav-link' href="{% url "register_app:user_login" %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="contanier">
      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>

django user login logout/user_login_logout/templates/register_app/index.html
{% extends "register_app/base.html" %}
{% block body_block%}
<div class="jumbotron">
  <h1>This is the index page</h1>

</div>
{% endblock %}

django user login logout/user_login_logout/templates/register_app/login.html
{% extends "register_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <form action="{% url 'register_app:user_login'%}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" value="login">

  </form>

</div>
{% endblock %}

django user login logout/user_login_logout/templates/register_app/register.html
{% extends "register_app/base.html"%}
{% block body_block %}

<div class="jumbotron">
  {% if registered %}
  <h2>Registered Successfully!!</h2>
  {% else %}
  <form enctype="multipart/form-data" method="post">
    {{user_form.as_p}}
    {{profile_form.as_p}}
    {% csrf_token %}
    <input type="submit" name="" value="register">
  </form>
  {% endif %}
</div>


{% endblock %}